# Generated by Django 2.2.7 on 2019-11-06 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountList',
            fields=[
                ('account_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=30)),
                ('account_num', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('account_kind', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('account_kind_other', models.CharField(max_length=20)),
                ('account_purpose', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('account_purpose_other', models.CharField(max_length=30)),
            ],
        ),
    ]
