# Generated by Django 2.2.7 on 2019-11-06 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterRegistApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlist',
            name='account_balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accountlist',
            name='account_kind',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='accountlist',
            name='account_kind_other',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountlist',
            name='account_num',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
        migrations.AlterField(
            model_name='accountlist',
            name='account_purpose',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='accountlist',
            name='account_purpose_other',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
