# Generated by Django 2.2.7 on 2019-11-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterRegistApp', '0002_auto_20191107_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlist',
            name='bank',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountlist',
            name='account_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
