# Generated by Django 2.2.7 on 2019-11-07 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterRegistApp', '0003_auto_20191107_0933'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountlist',
            table='AccountList',
        ),
    ]
